// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Enterprise_E_Commerce_Management_System.Models.Countries;
using System;
using System.Collections.Generic;

namespace Enterprise_E_Commerce_Management_System.Models;

public partial class Currency
{
    public int Id { get; set; }

    public string Code { get; set; }

    public string Name { get; set; }

    public decimal DollarRate { get; set; }

    public int CountryId { get; set; }
    public virtual Country Country { get; set; }
}