// <auto-generated />
using System;
using Enterprise_E_Commerce_Management_System.Infrastructures;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Enterprise_E_Commerce_Management_System.Migrations
{
    [DbContext(typeof(CommerceDbContext))]
    [Migration("20260208220510_UniqueProducts")]
    partial class UniqueProducts
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Enterprise_E_Commerce_Management_System.Models.ApplicationUserRoles.ApplicationPermission", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Module")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("Id")
                        .IsUnique();

                    b.ToTable("ApplicationPermissions");
                });

            modelBuilder.Entity("Enterprise_E_Commerce_Management_System.Models.ApplicationUserRoles.ApplicationUserRole", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Enterprise_E_Commerce_Management_System.Models.CartItems.CartItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CartId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("VariantId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CartId");

                    b.HasIndex("VariantId");

                    b.ToTable("CartItems", t =>
                        {
                            t.HasCheckConstraint("CK_CartItem_Quantity", "[UnitPrice] BETWEEN 1 AND 999999999999");
                        });
                });

            modelBuilder.Entity("Enterprise_E_Commerce_Management_System.Models.Carts.Cart", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CustomerId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.ToTable("Carts");
                });

            modelBuilder.Entity("Enterprise_E_Commerce_Management_System.Models.Categories.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsActive = true,
                            IsDeleted = false,
                            Name = "General"
                        },
                        new
                        {
                            Id = 2,
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Electronics"
                        },
                        new
                        {
                            Id = 3,
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Accessories"
                        },
                        new
                        {
                            Id = 4,
                            IsActive = false,
                            IsDeleted = false,
                            Name = "Archived"
                        });
                });

            modelBuilder.Entity("Enterprise_E_Commerce_Management_System.Models.Countries.Country", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Countries");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CurrencyCode = "AFN",
                            Name = "Afghanistan"
                        },
                        new
                        {
                            Id = 2,
                            CurrencyCode = "ALL",
                            Name = "Albania"
                        },
                        new
                        {
                            Id = 3,
                            CurrencyCode = "DZD",
                            Name = "Algeria"
                        },
                        new
                        {
                            Id = 4,
                            CurrencyCode = "EUR",
                            Name = "Andorra"
                        },
                        new
                        {
                            Id = 5,
                            CurrencyCode = "AOA",
                            Name = "Angola"
                        },
                        new
                        {
                            Id = 6,
                            CurrencyCode = "ARS",
                            Name = "Argentina"
                        },
                        new
                        {
                            Id = 7,
                            CurrencyCode = "AMD",
                            Name = "Armenia"
                        },
                        new
                        {
                            Id = 8,
                            CurrencyCode = "AUD",
                            Name = "Australia"
                        },
                        new
                        {
                            Id = 9,
                            CurrencyCode = "EUR",
                            Name = "Austria"
                        },
                        new
                        {
                            Id = 10,
                            CurrencyCode = "AZN",
                            Name = "Azerbaijan"
                        },
                        new
                        {
                            Id = 11,
                            CurrencyCode = "BHD",
                            Name = "Bahrain"
                        },
                        new
                        {
                            Id = 12,
                            CurrencyCode = "BDT",
                            Name = "Bangladesh"
                        },
                        new
                        {
                            Id = 13,
                            CurrencyCode = "BYN",
                            Name = "Belarus"
                        },
                        new
                        {
                            Id = 14,
                            CurrencyCode = "EUR",
                            Name = "Belgium"
                        },
                        new
                        {
                            Id = 15,
                            CurrencyCode = "BOB",
                            Name = "Bolivia"
                        },
                        new
                        {
                            Id = 16,
                            CurrencyCode = "BRL",
                            Name = "Brazil"
                        },
                        new
                        {
                            Id = 17,
                            CurrencyCode = "BGN",
                            Name = "Bulgaria"
                        },
                        new
                        {
                            Id = 18,
                            CurrencyCode = "CAD",
                            Name = "Canada"
                        },
                        new
                        {
                            Id = 19,
                            CurrencyCode = "CLP",
                            Name = "Chile"
                        },
                        new
                        {
                            Id = 20,
                            CurrencyCode = "CNY",
                            Name = "China"
                        },
                        new
                        {
                            Id = 21,
                            CurrencyCode = "COP",
                            Name = "Colombia"
                        },
                        new
                        {
                            Id = 22,
                            CurrencyCode = "EUR",
                            Name = "Croatia"
                        },
                        new
                        {
                            Id = 23,
                            CurrencyCode = "CUP",
                            Name = "Cuba"
                        },
                        new
                        {
                            Id = 24,
                            CurrencyCode = "EUR",
                            Name = "Cyprus"
                        },
                        new
                        {
                            Id = 25,
                            CurrencyCode = "CZK",
                            Name = "Czech Republic"
                        },
                        new
                        {
                            Id = 26,
                            CurrencyCode = "DKK",
                            Name = "Denmark"
                        },
                        new
                        {
                            Id = 27,
                            CurrencyCode = "DOP",
                            Name = "Dominican Republic"
                        },
                        new
                        {
                            Id = 28,
                            CurrencyCode = "USD",
                            Name = "Ecuador"
                        },
                        new
                        {
                            Id = 29,
                            CurrencyCode = "EGP",
                            Name = "Egypt"
                        },
                        new
                        {
                            Id = 30,
                            CurrencyCode = "USD",
                            Name = "El Salvador"
                        },
                        new
                        {
                            Id = 31,
                            CurrencyCode = "EUR",
                            Name = "Estonia"
                        },
                        new
                        {
                            Id = 32,
                            CurrencyCode = "ETB",
                            Name = "Ethiopia"
                        },
                        new
                        {
                            Id = 33,
                            CurrencyCode = "EUR",
                            Name = "Finland"
                        },
                        new
                        {
                            Id = 34,
                            CurrencyCode = "EUR",
                            Name = "France"
                        },
                        new
                        {
                            Id = 35,
                            CurrencyCode = "GEL",
                            Name = "Georgia"
                        },
                        new
                        {
                            Id = 36,
                            CurrencyCode = "EUR",
                            Name = "Germany"
                        },
                        new
                        {
                            Id = 37,
                            CurrencyCode = "GHS",
                            Name = "Ghana"
                        },
                        new
                        {
                            Id = 38,
                            CurrencyCode = "EUR",
                            Name = "Greece"
                        },
                        new
                        {
                            Id = 39,
                            CurrencyCode = "HUF",
                            Name = "Hungary"
                        },
                        new
                        {
                            Id = 40,
                            CurrencyCode = "ISK",
                            Name = "Iceland"
                        },
                        new
                        {
                            Id = 41,
                            CurrencyCode = "INR",
                            Name = "India"
                        },
                        new
                        {
                            Id = 42,
                            CurrencyCode = "IDR",
                            Name = "Indonesia"
                        },
                        new
                        {
                            Id = 43,
                            CurrencyCode = "IRR",
                            Name = "Iran"
                        },
                        new
                        {
                            Id = 44,
                            CurrencyCode = "IQD",
                            Name = "Iraq"
                        },
                        new
                        {
                            Id = 45,
                            CurrencyCode = "EUR",
                            Name = "Ireland"
                        },
                        new
                        {
                            Id = 46,
                            CurrencyCode = "EUR",
                            Name = "Italy"
                        },
                        new
                        {
                            Id = 47,
                            CurrencyCode = "JPY",
                            Name = "Japan"
                        },
                        new
                        {
                            Id = 48,
                            CurrencyCode = "JOD",
                            Name = "Jordan"
                        },
                        new
                        {
                            Id = 49,
                            CurrencyCode = "KZT",
                            Name = "Kazakhstan"
                        },
                        new
                        {
                            Id = 50,
                            CurrencyCode = "KES",
                            Name = "Kenya"
                        },
                        new
                        {
                            Id = 51,
                            CurrencyCode = "KWD",
                            Name = "Kuwait"
                        },
                        new
                        {
                            Id = 52,
                            CurrencyCode = "EUR",
                            Name = "Latvia"
                        },
                        new
                        {
                            Id = 53,
                            CurrencyCode = "LBP",
                            Name = "Lebanon"
                        },
                        new
                        {
                            Id = 54,
                            CurrencyCode = "LYD",
                            Name = "Libya"
                        },
                        new
                        {
                            Id = 55,
                            CurrencyCode = "EUR",
                            Name = "Lithuania"
                        },
                        new
                        {
                            Id = 56,
                            CurrencyCode = "MYR",
                            Name = "Malaysia"
                        },
                        new
                        {
                            Id = 57,
                            CurrencyCode = "MXN",
                            Name = "Mexico"
                        },
                        new
                        {
                            Id = 58,
                            CurrencyCode = "MAD",
                            Name = "Morocco"
                        },
                        new
                        {
                            Id = 59,
                            CurrencyCode = "EUR",
                            Name = "Netherlands"
                        },
                        new
                        {
                            Id = 60,
                            CurrencyCode = "NZD",
                            Name = "New Zealand"
                        },
                        new
                        {
                            Id = 61,
                            CurrencyCode = "NGN",
                            Name = "Nigeria"
                        },
                        new
                        {
                            Id = 62,
                            CurrencyCode = "NOK",
                            Name = "Norway"
                        },
                        new
                        {
                            Id = 63,
                            CurrencyCode = "OMR",
                            Name = "Oman"
                        },
                        new
                        {
                            Id = 64,
                            CurrencyCode = "PKR",
                            Name = "Pakistan"
                        },
                        new
                        {
                            Id = 65,
                            CurrencyCode = "ILS",
                            Name = "Palestine"
                        },
                        new
                        {
                            Id = 66,
                            CurrencyCode = "PEN",
                            Name = "Peru"
                        },
                        new
                        {
                            Id = 67,
                            CurrencyCode = "PHP",
                            Name = "Philippines"
                        },
                        new
                        {
                            Id = 68,
                            CurrencyCode = "PLN",
                            Name = "Poland"
                        },
                        new
                        {
                            Id = 69,
                            CurrencyCode = "EUR",
                            Name = "Portugal"
                        },
                        new
                        {
                            Id = 70,
                            CurrencyCode = "QAR",
                            Name = "Qatar"
                        },
                        new
                        {
                            Id = 71,
                            CurrencyCode = "RON",
                            Name = "Romania"
                        },
                        new
                        {
                            Id = 72,
                            CurrencyCode = "RUB",
                            Name = "Russia"
                        },
                        new
                        {
                            Id = 73,
                            CurrencyCode = "SAR",
                            Name = "Saudi Arabia"
                        },
                        new
                        {
                            Id = 74,
                            CurrencyCode = "RSD",
                            Name = "Serbia"
                        },
                        new
                        {
                            Id = 75,
                            CurrencyCode = "SGD",
                            Name = "Singapore"
                        },
                        new
                        {
                            Id = 76,
                            CurrencyCode = "EUR",
                            Name = "Slovakia"
                        },
                        new
                        {
                            Id = 77,
                            CurrencyCode = "ZAR",
                            Name = "South Africa"
                        },
                        new
                        {
                            Id = 78,
                            CurrencyCode = "EUR",
                            Name = "Spain"
                        },
                        new
                        {
                            Id = 79,
                            CurrencyCode = "SDG",
                            Name = "Sudan"
                        },
                        new
                        {
                            Id = 80,
                            CurrencyCode = "SEK",
                            Name = "Sweden"
                        },
                        new
                        {
                            Id = 81,
                            CurrencyCode = "CHF",
                            Name = "Switzerland"
                        },
                        new
                        {
                            Id = 82,
                            CurrencyCode = "SYP",
                            Name = "Syria"
                        },
                        new
                        {
                            Id = 83,
                            CurrencyCode = "THB",
                            Name = "Thailand"
                        },
                        new
                        {
                            Id = 84,
                            CurrencyCode = "TND",
                            Name = "Tunisia"
                        },
                        new
                        {
                            Id = 85,
                            CurrencyCode = "TRY",
                            Name = "Turkey"
                        },
                        new
                        {
                            Id = 86,
                            CurrencyCode = "UAH",
                            Name = "Ukraine"
                        },
                        new
                        {
                            Id = 87,
                            CurrencyCode = "AED",
                            Name = "United Arab Emirates"
                        },
                        new
                        {
                            Id = 88,
                            CurrencyCode = "GBP",
                            Name = "United Kingdom"
                        },
                        new
                        {
                            Id = 89,
                            CurrencyCode = "USD",
                            Name = "United States"
                        },
                        new
                        {
                            Id = 90,
                            CurrencyCode = "VES",
                            Name = "Venezuela"
                        },
                        new
                        {
                            Id = 91,
                            CurrencyCode = "VND",
                            Name = "Vietnam"
                        },
                        new
                        {
                            Id = 92,
                            CurrencyCode = "YER",
                            Name = "Yemen"
                        },
                        new
                        {
                            Id = 93,
                            CurrencyCode = "ZMW",
                            Name = "Zambia"
                        },
                        new
                        {
                            Id = 94,
                            CurrencyCode = "ZWL",
                            Name = "Zimbabwe"
                        },
                        new
                        {
                            Id = 95,
                            CurrencyCode = "BSD",
                            Name = "Bahamas"
                        },
                        new
                        {
                            Id = 96,
                            CurrencyCode = "BBD",
                            Name = "Barbados"
                        },
                        new
                        {
                            Id = 97,
                            CurrencyCode = "BZD",
                            Name = "Belize"
                        },
                        new
                        {
                            Id = 98,
                            CurrencyCode = "XOF",
                            Name = "Benin"
                        },
                        new
                        {
                            Id = 99,
                            CurrencyCode = "BTN",
                            Name = "Bhutan"
                        },
                        new
                        {
                            Id = 100,
                            CurrencyCode = "BAM",
                            Name = "Bosnia and Herzegovina"
                        },
                        new
                        {
                            Id = 101,
                            CurrencyCode = "BWP",
                            Name = "Botswana"
                        },
                        new
                        {
                            Id = 102,
                            CurrencyCode = "BND",
                            Name = "Brunei"
                        },
                        new
                        {
                            Id = 103,
                            CurrencyCode = "XOF",
                            Name = "Burkina Faso"
                        },
                        new
                        {
                            Id = 104,
                            CurrencyCode = "BIF",
                            Name = "Burundi"
                        },
                        new
                        {
                            Id = 105,
                            CurrencyCode = "KHR",
                            Name = "Cambodia"
                        },
                        new
                        {
                            Id = 106,
                            CurrencyCode = "XAF",
                            Name = "Cameroon"
                        },
                        new
                        {
                            Id = 107,
                            CurrencyCode = "CVE",
                            Name = "Cape Verde"
                        },
                        new
                        {
                            Id = 108,
                            CurrencyCode = "XAF",
                            Name = "Central African Republic"
                        },
                        new
                        {
                            Id = 109,
                            CurrencyCode = "XAF",
                            Name = "Chad"
                        },
                        new
                        {
                            Id = 110,
                            CurrencyCode = "KMF",
                            Name = "Comoros"
                        },
                        new
                        {
                            Id = 111,
                            CurrencyCode = "XAF",
                            Name = "Congo"
                        },
                        new
                        {
                            Id = 112,
                            CurrencyCode = "CRC",
                            Name = "Costa Rica"
                        },
                        new
                        {
                            Id = 113,
                            CurrencyCode = "XOF",
                            Name = "Côte d'Ivoire"
                        },
                        new
                        {
                            Id = 114,
                            CurrencyCode = "DJF",
                            Name = "Djibouti"
                        },
                        new
                        {
                            Id = 115,
                            CurrencyCode = "XAF",
                            Name = "Equatorial Guinea"
                        },
                        new
                        {
                            Id = 116,
                            CurrencyCode = "ERN",
                            Name = "Eritrea"
                        },
                        new
                        {
                            Id = 117,
                            CurrencyCode = "FJD",
                            Name = "Fiji"
                        },
                        new
                        {
                            Id = 118,
                            CurrencyCode = "XAF",
                            Name = "Gabon"
                        },
                        new
                        {
                            Id = 119,
                            CurrencyCode = "GMD",
                            Name = "Gambia"
                        },
                        new
                        {
                            Id = 120,
                            CurrencyCode = "XCD",
                            Name = "Grenada"
                        },
                        new
                        {
                            Id = 121,
                            CurrencyCode = "GTQ",
                            Name = "Guatemala"
                        },
                        new
                        {
                            Id = 122,
                            CurrencyCode = "GNF",
                            Name = "Guinea"
                        },
                        new
                        {
                            Id = 123,
                            CurrencyCode = "XOF",
                            Name = "Guinea-Bissau"
                        },
                        new
                        {
                            Id = 124,
                            CurrencyCode = "GYD",
                            Name = "Guyana"
                        },
                        new
                        {
                            Id = 125,
                            CurrencyCode = "HTG",
                            Name = "Haiti"
                        },
                        new
                        {
                            Id = 126,
                            CurrencyCode = "HNL",
                            Name = "Honduras"
                        },
                        new
                        {
                            Id = 127,
                            CurrencyCode = "JMD",
                            Name = "Jamaica"
                        },
                        new
                        {
                            Id = 128,
                            CurrencyCode = "AUD",
                            Name = "Kiribati"
                        },
                        new
                        {
                            Id = 129,
                            CurrencyCode = "KGS",
                            Name = "Kyrgyzstan"
                        },
                        new
                        {
                            Id = 130,
                            CurrencyCode = "LAK",
                            Name = "Laos"
                        },
                        new
                        {
                            Id = 131,
                            CurrencyCode = "LSL",
                            Name = "Lesotho"
                        },
                        new
                        {
                            Id = 132,
                            CurrencyCode = "LRD",
                            Name = "Liberia"
                        },
                        new
                        {
                            Id = 133,
                            CurrencyCode = "CHF",
                            Name = "Liechtenstein"
                        },
                        new
                        {
                            Id = 134,
                            CurrencyCode = "EUR",
                            Name = "Luxembourg"
                        },
                        new
                        {
                            Id = 135,
                            CurrencyCode = "MGA",
                            Name = "Madagascar"
                        },
                        new
                        {
                            Id = 136,
                            CurrencyCode = "MWK",
                            Name = "Malawi"
                        },
                        new
                        {
                            Id = 137,
                            CurrencyCode = "MVR",
                            Name = "Maldives"
                        },
                        new
                        {
                            Id = 138,
                            CurrencyCode = "XOF",
                            Name = "Mali"
                        },
                        new
                        {
                            Id = 139,
                            CurrencyCode = "EUR",
                            Name = "Malta"
                        },
                        new
                        {
                            Id = 140,
                            CurrencyCode = "USD",
                            Name = "Marshall Islands"
                        },
                        new
                        {
                            Id = 141,
                            CurrencyCode = "MRU",
                            Name = "Mauritania"
                        },
                        new
                        {
                            Id = 142,
                            CurrencyCode = "MUR",
                            Name = "Mauritius"
                        },
                        new
                        {
                            Id = 143,
                            CurrencyCode = "USD",
                            Name = "Micronesia"
                        },
                        new
                        {
                            Id = 144,
                            CurrencyCode = "MDL",
                            Name = "Moldova"
                        },
                        new
                        {
                            Id = 145,
                            CurrencyCode = "EUR",
                            Name = "Monaco"
                        },
                        new
                        {
                            Id = 146,
                            CurrencyCode = "MNT",
                            Name = "Mongolia"
                        },
                        new
                        {
                            Id = 147,
                            CurrencyCode = "EUR",
                            Name = "Montenegro"
                        },
                        new
                        {
                            Id = 148,
                            CurrencyCode = "MZN",
                            Name = "Mozambique"
                        },
                        new
                        {
                            Id = 149,
                            CurrencyCode = "MMK",
                            Name = "Myanmar"
                        },
                        new
                        {
                            Id = 150,
                            CurrencyCode = "NAD",
                            Name = "Namibia"
                        },
                        new
                        {
                            Id = 151,
                            CurrencyCode = "AUD",
                            Name = "Nauru"
                        },
                        new
                        {
                            Id = 152,
                            CurrencyCode = "NPR",
                            Name = "Nepal"
                        },
                        new
                        {
                            Id = 153,
                            CurrencyCode = "NIO",
                            Name = "Nicaragua"
                        },
                        new
                        {
                            Id = 154,
                            CurrencyCode = "XOF",
                            Name = "Niger"
                        },
                        new
                        {
                            Id = 155,
                            CurrencyCode = "KPW",
                            Name = "North Korea"
                        },
                        new
                        {
                            Id = 156,
                            CurrencyCode = "MKD",
                            Name = "North Macedonia"
                        },
                        new
                        {
                            Id = 157,
                            CurrencyCode = "PAB",
                            Name = "Panama"
                        },
                        new
                        {
                            Id = 158,
                            CurrencyCode = "PGK",
                            Name = "Papua New Guinea"
                        },
                        new
                        {
                            Id = 159,
                            CurrencyCode = "PYG",
                            Name = "Paraguay"
                        },
                        new
                        {
                            Id = 160,
                            CurrencyCode = "RWF",
                            Name = "Rwanda"
                        },
                        new
                        {
                            Id = 161,
                            CurrencyCode = "XCD",
                            Name = "Saint Lucia"
                        },
                        new
                        {
                            Id = 162,
                            CurrencyCode = "WST",
                            Name = "Samoa"
                        },
                        new
                        {
                            Id = 163,
                            CurrencyCode = "EUR",
                            Name = "San Marino"
                        },
                        new
                        {
                            Id = 164,
                            CurrencyCode = "STN",
                            Name = "Sao Tome and Principe"
                        },
                        new
                        {
                            Id = 165,
                            CurrencyCode = "XOF",
                            Name = "Senegal"
                        },
                        new
                        {
                            Id = 166,
                            CurrencyCode = "SCR",
                            Name = "Seychelles"
                        },
                        new
                        {
                            Id = 167,
                            CurrencyCode = "SLL",
                            Name = "Sierra Leone"
                        },
                        new
                        {
                            Id = 168,
                            CurrencyCode = "EUR",
                            Name = "Slovenia"
                        },
                        new
                        {
                            Id = 169,
                            CurrencyCode = "SBD",
                            Name = "Solomon Islands"
                        },
                        new
                        {
                            Id = 170,
                            CurrencyCode = "SOS",
                            Name = "Somalia"
                        },
                        new
                        {
                            Id = 171,
                            CurrencyCode = "SSP",
                            Name = "South Sudan"
                        },
                        new
                        {
                            Id = 172,
                            CurrencyCode = "LKR",
                            Name = "Sri Lanka"
                        },
                        new
                        {
                            Id = 173,
                            CurrencyCode = "SRD",
                            Name = "Suriname"
                        },
                        new
                        {
                            Id = 174,
                            CurrencyCode = "SZL",
                            Name = "Eswatini"
                        },
                        new
                        {
                            Id = 175,
                            CurrencyCode = "TJS",
                            Name = "Tajikistan"
                        },
                        new
                        {
                            Id = 176,
                            CurrencyCode = "TZS",
                            Name = "Tanzania"
                        },
                        new
                        {
                            Id = 177,
                            CurrencyCode = "USD",
                            Name = "Timor-Leste"
                        },
                        new
                        {
                            Id = 178,
                            CurrencyCode = "XOF",
                            Name = "Togo"
                        },
                        new
                        {
                            Id = 179,
                            CurrencyCode = "TOP",
                            Name = "Tonga"
                        },
                        new
                        {
                            Id = 180,
                            CurrencyCode = "TTD",
                            Name = "Trinidad and Tobago"
                        },
                        new
                        {
                            Id = 181,
                            CurrencyCode = "TMT",
                            Name = "Turkmenistan"
                        },
                        new
                        {
                            Id = 182,
                            CurrencyCode = "AUD",
                            Name = "Tuvalu"
                        },
                        new
                        {
                            Id = 183,
                            CurrencyCode = "UGX",
                            Name = "Uganda"
                        },
                        new
                        {
                            Id = 184,
                            CurrencyCode = "UYU",
                            Name = "Uruguay"
                        },
                        new
                        {
                            Id = 185,
                            CurrencyCode = "UZS",
                            Name = "Uzbekistan"
                        },
                        new
                        {
                            Id = 186,
                            CurrencyCode = "VUV",
                            Name = "Vanuatu"
                        },
                        new
                        {
                            Id = 187,
                            CurrencyCode = "EUR",
                            Name = "Vatican City"
                        },
                        new
                        {
                            Id = 188,
                            CurrencyCode = "MAD",
                            Name = "Western Sahara"
                        },
                        new
                        {
                            Id = 189,
                            CurrencyCode = "XCD",
                            Name = "Saint Vincent and the Grenadines"
                        },
                        new
                        {
                            Id = 190,
                            CurrencyCode = "XCD",
                            Name = "Antigua and Barbuda"
                        },
                        new
                        {
                            Id = 191,
                            CurrencyCode = "XCD",
                            Name = "Dominica"
                        },
                        new
                        {
                            Id = 192,
                            CurrencyCode = "XCD",
                            Name = "Saint Kitts and Nevis"
                        },
                        new
                        {
                            Id = 193,
                            CurrencyCode = "KRW",
                            Name = "South Korea"
                        },
                        new
                        {
                            Id = 194,
                            CurrencyCode = "TWD",
                            Name = "Taiwan"
                        },
                        new
                        {
                            Id = 195,
                            CurrencyCode = "EUR",
                            Name = "Kosovo"
                        });
                });

            modelBuilder.Entity("Enterprise_E_Commerce_Management_System.Models.Coupons.Coupon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte>("DiscountType")
                        .HasColumnType("tinyint")
                        .HasComment("Percentage = 1,\nFixedAmount = 2,\nFreeShipping = 3");

                    b.Property<decimal>("DiscountValue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("ExpiryDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Coupons");
                });

            modelBuilder.Entity("Enterprise_E_Commerce_Management_System.Models.Couriers.Courier", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("ShippingProviderId")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("ShippingProviderId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Couriers");
                });

            modelBuilder.Entity("Enterprise_E_Commerce_Management_System.Models.Customers.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("CreateDate")
                        .HasColumnType("date");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.HasKey("Id");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("Enterprise_E_Commerce_Management_System.Models.Orders.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AccessToken")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("CouponId")
                        .HasColumnType("int");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("OrderNumber")
                        .HasColumnType("nvarchar(450)");

                    b.Property<byte>("OrderStatus")
                        .HasColumnType("tinyint")
                        .HasComment("Pending=1,\nPaid=2,\nShipped=3,\nCompleted=4\nCancelled=5");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("AccessToken")
                        .IsUnique()
                        .HasFilter("[AccessToken] IS NOT NULL");

                    b.HasIndex("CouponId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("OrderNumber")
                        .IsUnique()
                        .HasFilter("[OrderNumber] IS NOT NULL");

                    b.ToTable("Orders", t =>
                        {
                            t.HasTrigger("trg_AfterInsertOrder");

                            t.HasCheckConstraint("CK_Order_TotalAmount", "[TotalAmount] BETWEEN 1 AND 999999999999");
                        });

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("Enterprise_E_Commerce_Management_System.Models.Orders.OrderItem", b =>
                {
                    b.Property<int>("OrderItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderItemId"));

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("VariantId")
                        .HasColumnType("int");

                    b.HasKey("OrderItemId");

                    b.HasIndex("OrderId");

                    b.HasIndex("VariantId");

                    b.ToTable("OrderItems", t =>
                        {
                            t.HasCheckConstraint("CK_OrderItem_Price", "[Price] BETWEEN 1 AND 999999999999");

                            t.HasCheckConstraint("CK_OrderItem_Quantity", "[Quantity] BETWEEN 0 AND 2147483647");
                        });
                });

            modelBuilder.Entity("Enterprise_E_Commerce_Management_System.Models.Orders.OrderReturn", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CourierId")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("PickedUpAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("RequestedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ReturnedAt")
                        .HasColumnType("datetime2");

                    b.Property<byte>("Status")
                        .HasColumnType("tinyint")
                        .HasComment(" Requested = 1, PickedUp = 2, Returned = 3, Rejected = 4");

                    b.HasKey("Id");

                    b.HasIndex("CourierId");

                    b.HasIndex("OrderId")
                        .IsUnique();

                    b.ToTable("OrderReturns");
                });

            modelBuilder.Entity("Enterprise_E_Commerce_Management_System.Models.Payments.Payment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("datetime2");

                    b.Property<byte>("PaymentMethod")
                        .HasColumnType("tinyint")
                        .HasComment("CashOnDelivery = 1,\nCreditCard = 2,\nWallet = 3");

                    b.Property<byte>("PaymentStatus")
                        .HasColumnType("tinyint")
                        .HasComment("\nPending = 1,\nPaid = 2,\nFailed = 3,\nRefunded = 4");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("OrderId");

                    b.ToTable("Payments", t =>
                        {
                            t.HasCheckConstraint("CK_Payment_Amount", "[Amount] BETWEEN 1 AND 999999999999");
                        });
                });

            modelBuilder.Entity("Enterprise_E_Commerce_Management_System.Models.Permissions.ApplicationRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "b8f9f7e2-9f01-4d6b-9b63-1a7c5d111111",
                            ConcurrencyStamp = "3e6f9c4a-7d2b-4c8f-9a41-8c1f2b7a01a1",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = "b8f9f7e2-9f01-4d6b-9b63-1a7c5d222222",
                            ConcurrencyStamp = "91b4e2d7-5f3c-4a1b-8e62-0a9c3d4f02b2",
                            Name = "Manager",
                            NormalizedName = "MANAGER"
                        },
                        new
                        {
                            Id = "b8f9f7e2-9f01-4d6b-9b63-1a7c5d333333",
                            ConcurrencyStamp = "c7a1f3e9-8b6d-4c52-9d14-6f2e8a3b03c3",
                            Name = "Support",
                            NormalizedName = "SUPPORT"
                        },
                        new
                        {
                            Id = "b8f9f7e2-9f01-4d6b-9b63-1a7c5d444444",
                            ConcurrencyStamp = "f2d9a8b4-1e7c-4f63-8a25-b1c6e4d904d4",
                            Name = "Staff",
                            NormalizedName = "STAFF"
                        },
                        new
                        {
                            Id = "b7f9f7e1-9f01-4d6b-9b63-1a7c5d444444",
                            ConcurrencyStamp = "f2d9a8b4-1e7c-4f63-8a25-b1c6e2d000d4",
                            Name = "Courier",
                            NormalizedName = "COURIER"
                        });
                });

            modelBuilder.Entity("Enterprise_E_Commerce_Management_System.Models.Permissions.ApplicationRolePermission", b =>
                {
                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("PermissionId")
                        .HasColumnType("int");

                    b.HasKey("RoleId", "PermissionId");

                    b.HasIndex("PermissionId");

                    b.ToTable("ApplicationRolePermissions");
                });

            modelBuilder.Entity("Enterprise_E_Commerce_Management_System.Models.Permissions.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CountryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Enterprise_E_Commerce_Management_System.Models.Permissions.ApplicationUserPermission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("PermissionId")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("PermissionId");

                    b.HasIndex("UserId");

                    b.ToTable("ApplicationUserPermissions");
                });

            modelBuilder.Entity("Enterprise_E_Commerce_Management_System.Models.Products.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateOnly>("CreateDate")
                        .HasColumnType("date");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ImageName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.HasIndex("ImageName")
                        .IsUnique();

                    b.HasIndex("CategoryId", "Name")
                        .IsUnique();

                    b.ToTable("Products");
                });

            modelBuilder.Entity("Enterprise_E_Commerce_Management_System.Models.Reviews.Review", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<DateTime>("ReviewDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("ProductId");

                    b.ToTable("Reviews", t =>
                        {
                            t.HasCheckConstraint("CK_Review_Comment", "LEN([Comment]) > 1");

                            t.HasCheckConstraint("CK_Review_Rating", "[Rating] BETWEEN 1 AND 5");
                        });
                });

            modelBuilder.Entity("Enterprise_E_Commerce_Management_System.Models.Shipments.CountryDeliveryFee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CountryId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<decimal>("MaxFee")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("MinFee")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CountryId")
                        .IsUnique();

                    b.ToTable("CountryDeliveryFees");
                });

            modelBuilder.Entity("Enterprise_E_Commerce_Management_System.Models.Shipments.Shipment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("AssignedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("CourierId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeliveredDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<byte>("Status")
                        .HasColumnType("tinyint")
                        .HasComment("AssignedForDelivery = 1, Delivered = 2, DeliveryFailed = 3");

                    b.HasKey("Id");

                    b.HasIndex("CourierId");

                    b.HasIndex("OrderId");

                    b.ToTable("Shipments");
                });

            modelBuilder.Entity("Enterprise_E_Commerce_Management_System.Models.ShippingProviders.ShippingProvider", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("ShippingProviders");
                });

            modelBuilder.Entity("Enterprise_E_Commerce_Management_System.Models.VariantAttributes.VariantAttribute", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<byte>("DisplayType")
                        .HasColumnType("tinyint")
                        .HasComment("Text = 1,  Dropdown = 2, Color = 3,  Radio = 4,  Checkbox = 5");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("VariantId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("VariantId", "Name");

                    b.ToTable("VariantAttributes");
                });

            modelBuilder.Entity("Enterprise_E_Commerce_Management_System.Models.Variants.Variant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Cost")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<decimal>("Price")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<string>("SKU")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("SKU")
                        .IsUnique();

                    b.ToTable("Variants", t =>
                        {
                            t.HasCheckConstraint("CK_Variant_Cost", "[Cost] BETWEEN 1 AND 999999999999");

                            t.HasCheckConstraint("CK_Variant_Price", "[Price] BETWEEN 1 AND 999999999999");

                            t.HasCheckConstraint("CK_Variant_StockQuantity", "[StockQuantity] BETWEEN 0 AND 2147483647");
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Enterprise_E_Commerce_Management_System.Models.ApplicationUserRoles.ApplicationUserRole", b =>
                {
                    b.HasOne("Enterprise_E_Commerce_Management_System.Models.Permissions.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Enterprise_E_Commerce_Management_System.Models.Permissions.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Enterprise_E_Commerce_Management_System.Models.CartItems.CartItem", b =>
                {
                    b.HasOne("Enterprise_E_Commerce_Management_System.Models.Carts.Cart", "Cart")
                        .WithMany("CartItems")
                        .HasForeignKey("CartId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Enterprise_E_Commerce_Management_System.Models.Variants.Variant", "Variant")
                        .WithMany()
                        .HasForeignKey("VariantId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Cart");

                    b.Navigation("Variant");
                });

            modelBuilder.Entity("Enterprise_E_Commerce_Management_System.Models.Carts.Cart", b =>
                {
                    b.HasOne("Enterprise_E_Commerce_Management_System.Models.Customers.Customer", "Customer")
                        .WithMany("Carts")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("Enterprise_E_Commerce_Management_System.Models.Couriers.Courier", b =>
                {
                    b.HasOne("Enterprise_E_Commerce_Management_System.Models.ShippingProviders.ShippingProvider", "ShippingProvider")
                        .WithMany("Couriers")
                        .HasForeignKey("ShippingProviderId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Enterprise_E_Commerce_Management_System.Models.Permissions.ApplicationUser", "User")
                        .WithOne()
                        .HasForeignKey("Enterprise_E_Commerce_Management_System.Models.Couriers.Courier", "UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("ShippingProvider");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Enterprise_E_Commerce_Management_System.Models.Customers.Customer", b =>
                {
                    b.OwnsOne("Enterprise_E_Commerce_Management_System.Models.Customers.Address", "Address", b1 =>
                        {
                            b1.Property<int>("CustomerId")
                                .HasColumnType("int");

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)");

                            b1.Property<int>("CountryId")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int")
                                .HasDefaultValue(29);

                            b1.Property<string>("PostalCode")
                                .HasMaxLength(20)
                                .HasColumnType("nvarchar(20)");

                            b1.Property<string>("Street")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("nvarchar(200)");

                            b1.HasKey("CustomerId");

                            b1.HasIndex("CountryId");

                            b1.ToTable("Customers");

                            b1.HasOne("Enterprise_E_Commerce_Management_System.Models.Countries.Country", "Country")
                                .WithMany()
                                .HasForeignKey("CountryId")
                                .OnDelete(DeleteBehavior.NoAction)
                                .IsRequired();

                            b1.WithOwner()
                                .HasForeignKey("CustomerId");

                            b1.Navigation("Country");
                        });

                    b.OwnsOne("Enterprise_E_Commerce_Management_System.Models.Customers.FullName", "FullName", b1 =>
                        {
                            b1.Property<int>("CustomerId")
                                .HasColumnType("int");

                            b1.Property<string>("FirstName")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)");

                            b1.Property<string>("LastName")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)");

                            b1.Property<string>("MiddleName")
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)");

                            b1.HasKey("CustomerId");

                            b1.ToTable("Customers");

                            b1.WithOwner()
                                .HasForeignKey("CustomerId");
                        });

                    b.Navigation("Address")
                        .IsRequired();

                    b.Navigation("FullName")
                        .IsRequired();
                });

            modelBuilder.Entity("Enterprise_E_Commerce_Management_System.Models.Orders.Order", b =>
                {
                    b.HasOne("Enterprise_E_Commerce_Management_System.Models.Coupons.Coupon", "Coupon")
                        .WithMany("Orders")
                        .HasForeignKey("CouponId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Enterprise_E_Commerce_Management_System.Models.Customers.Customer", "Customer")
                        .WithMany("Orders")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.OwnsOne("Enterprise_E_Commerce_Management_System.Models.Customers.Address", "Address", b1 =>
                        {
                            b1.Property<int>("OrderId")
                                .HasColumnType("int");

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)");

                            b1.Property<int>("CountryId")
                                .HasColumnType("int");

                            b1.Property<string>("PostalCode")
                                .HasMaxLength(20)
                                .HasColumnType("nvarchar(20)");

                            b1.Property<string>("Street")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)");

                            b1.HasKey("OrderId");

                            b1.HasIndex("CountryId");

                            b1.ToTable("Orders");

                            b1.HasOne("Enterprise_E_Commerce_Management_System.Models.Countries.Country", "Country")
                                .WithMany()
                                .HasForeignKey("CountryId")
                                .OnDelete(DeleteBehavior.NoAction)
                                .IsRequired();

                            b1.WithOwner()
                                .HasForeignKey("OrderId");

                            b1.Navigation("Country");
                        });

                    b.Navigation("Address")
                        .IsRequired();

                    b.Navigation("Coupon");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("Enterprise_E_Commerce_Management_System.Models.Orders.OrderItem", b =>
                {
                    b.HasOne("Enterprise_E_Commerce_Management_System.Models.Orders.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Enterprise_E_Commerce_Management_System.Models.Variants.Variant", "Variant")
                        .WithMany()
                        .HasForeignKey("VariantId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Variant");
                });

            modelBuilder.Entity("Enterprise_E_Commerce_Management_System.Models.Orders.OrderReturn", b =>
                {
                    b.HasOne("Enterprise_E_Commerce_Management_System.Models.Couriers.Courier", "Courier")
                        .WithMany()
                        .HasForeignKey("CourierId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Enterprise_E_Commerce_Management_System.Models.Orders.Order", "Order")
                        .WithOne()
                        .HasForeignKey("Enterprise_E_Commerce_Management_System.Models.Orders.OrderReturn", "OrderId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Courier");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("Enterprise_E_Commerce_Management_System.Models.Payments.Payment", b =>
                {
                    b.HasOne("Enterprise_E_Commerce_Management_System.Models.Customers.Customer", "Customer")
                        .WithMany("Payments")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Enterprise_E_Commerce_Management_System.Models.Orders.Order", "Order")
                        .WithMany("Payments")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("Enterprise_E_Commerce_Management_System.Models.Permissions.ApplicationRolePermission", b =>
                {
                    b.HasOne("Enterprise_E_Commerce_Management_System.Models.ApplicationUserRoles.ApplicationPermission", "Permission")
                        .WithMany("RolePermissions")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Enterprise_E_Commerce_Management_System.Models.Permissions.ApplicationRole", "Role")
                        .WithMany("RolePermissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Permission");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Enterprise_E_Commerce_Management_System.Models.Permissions.ApplicationUser", b =>
                {
                    b.HasOne("Enterprise_E_Commerce_Management_System.Models.Countries.Country", "Country")
                        .WithMany()
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Country");
                });

            modelBuilder.Entity("Enterprise_E_Commerce_Management_System.Models.Permissions.ApplicationUserPermission", b =>
                {
                    b.HasOne("Enterprise_E_Commerce_Management_System.Models.ApplicationUserRoles.ApplicationPermission", "Permission")
                        .WithMany("UserPermissions")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Enterprise_E_Commerce_Management_System.Models.Permissions.ApplicationUser", "User")
                        .WithMany("UserPermissions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Permission");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Enterprise_E_Commerce_Management_System.Models.Products.Product", b =>
                {
                    b.HasOne("Enterprise_E_Commerce_Management_System.Models.Categories.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Enterprise_E_Commerce_Management_System.Models.Reviews.Review", b =>
                {
                    b.HasOne("Enterprise_E_Commerce_Management_System.Models.Customers.Customer", "Customer")
                        .WithMany("Reviews")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Enterprise_E_Commerce_Management_System.Models.Products.Product", "Product")
                        .WithMany("Reviews")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Enterprise_E_Commerce_Management_System.Models.Shipments.CountryDeliveryFee", b =>
                {
                    b.HasOne("Enterprise_E_Commerce_Management_System.Models.Countries.Country", "Country")
                        .WithOne()
                        .HasForeignKey("Enterprise_E_Commerce_Management_System.Models.Shipments.CountryDeliveryFee", "CountryId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Country");
                });

            modelBuilder.Entity("Enterprise_E_Commerce_Management_System.Models.Shipments.Shipment", b =>
                {
                    b.HasOne("Enterprise_E_Commerce_Management_System.Models.Couriers.Courier", "Courier")
                        .WithMany("Shipments")
                        .HasForeignKey("CourierId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Enterprise_E_Commerce_Management_System.Models.Orders.Order", "Order")
                        .WithMany("Shipments")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Courier");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("Enterprise_E_Commerce_Management_System.Models.VariantAttributes.VariantAttribute", b =>
                {
                    b.HasOne("Enterprise_E_Commerce_Management_System.Models.Variants.Variant", "Variant")
                        .WithMany("Attributes")
                        .HasForeignKey("VariantId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Variant");
                });

            modelBuilder.Entity("Enterprise_E_Commerce_Management_System.Models.Variants.Variant", b =>
                {
                    b.HasOne("Enterprise_E_Commerce_Management_System.Models.Products.Product", "Product")
                        .WithMany("Variants")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Enterprise_E_Commerce_Management_System.Models.Permissions.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Enterprise_E_Commerce_Management_System.Models.Permissions.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Enterprise_E_Commerce_Management_System.Models.Permissions.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Enterprise_E_Commerce_Management_System.Models.Permissions.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("Enterprise_E_Commerce_Management_System.Models.ApplicationUserRoles.ApplicationPermission", b =>
                {
                    b.Navigation("RolePermissions");

                    b.Navigation("UserPermissions");
                });

            modelBuilder.Entity("Enterprise_E_Commerce_Management_System.Models.Carts.Cart", b =>
                {
                    b.Navigation("CartItems");
                });

            modelBuilder.Entity("Enterprise_E_Commerce_Management_System.Models.Categories.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("Enterprise_E_Commerce_Management_System.Models.Coupons.Coupon", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("Enterprise_E_Commerce_Management_System.Models.Couriers.Courier", b =>
                {
                    b.Navigation("Shipments");
                });

            modelBuilder.Entity("Enterprise_E_Commerce_Management_System.Models.Customers.Customer", b =>
                {
                    b.Navigation("Carts");

                    b.Navigation("Orders");

                    b.Navigation("Payments");

                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("Enterprise_E_Commerce_Management_System.Models.Orders.Order", b =>
                {
                    b.Navigation("OrderItems");

                    b.Navigation("Payments");

                    b.Navigation("Shipments");
                });

            modelBuilder.Entity("Enterprise_E_Commerce_Management_System.Models.Permissions.ApplicationRole", b =>
                {
                    b.Navigation("RolePermissions");
                });

            modelBuilder.Entity("Enterprise_E_Commerce_Management_System.Models.Permissions.ApplicationUser", b =>
                {
                    b.Navigation("UserPermissions");
                });

            modelBuilder.Entity("Enterprise_E_Commerce_Management_System.Models.Products.Product", b =>
                {
                    b.Navigation("Reviews");

                    b.Navigation("Variants");
                });

            modelBuilder.Entity("Enterprise_E_Commerce_Management_System.Models.ShippingProviders.ShippingProvider", b =>
                {
                    b.Navigation("Couriers");
                });

            modelBuilder.Entity("Enterprise_E_Commerce_Management_System.Models.Variants.Variant", b =>
                {
                    b.Navigation("Attributes");
                });
#pragma warning restore 612, 618
        }
    }
}
